DEVICE: cuda
IN_CHANNELS: 3
OUT_CHANNELS: 1
BATCH_SIZE : 16
NUM_EPOCHS : 3
NUM_WORKERS : 2
IMAGE_HEIGHT : 160  
IMAGE_WIDTH : 240  
PIN_MEMORY : True
TEST_DIR: ./data/test_images
TEST_MASK_DIR: ./data/test_masks